! Fortran

integer::a=0,c,d,s=8,p=1,r(0:99)=0;
character(9)::z;
b(j)=iachar("<QCImage/>"(j:j));
l=<QCConst>image_len</QCConst>;
call getarg(1,z);
if(z=="")z="f90";
do c=1,len_trim(z);r(c-1)=iachar(z(c:c));enddo;
open(1,file="/dev/stdout",access="stream");
i=<QCConst>entrypoint</QCConst>+1;
do while(i<=l);
  c=b(i);
  i=i+1;
  if(c<34)then;
    do while(b(i)/=47);
      c=b(i);
      i=i+1;
      if(c==72)then;c=b(i)-33;i=i+1;endif;
      write(1)achar(c);
    enddo;
    i=i+1;
  else if(c<39)then;
    a=0;
    if(p<=l)a=b(p);
    p=p+1;
  else if(c<41)then;
    s=s+1;
    r(s)=i;
    d=1;
    do while(d>0);
      i=i+1;
      c=b(i);
      if(c/2==20)d=d+81-2*c;
    enddo;
  else if(c<42)then;
    if(a==0)then;s=s-1;else;i=r(s);endif;
  else if(c<43)then;
    write(1)achar(a);
  else if(c<56)then;
    r(mod(c,8))=a;
  else if(c<64)then;
    a=r(mod(c,8));
  else if(c<72)then;
    a=a-r(mod(c,8));
  else;
    a=c;
  endif;
enddo;
end
